In [0]:
# Next Attempt 
import numpy as np
import pandas as pd
f=open("/content/PCA-3.csv")
data=[]
label=[]
temp=0;
for i in f:
    if(temp==0):
        temp=1
        continue
    l=i.split(",")
    label.append(float(l[-1][0]))
    l=l[:-1]
    l=[float(j) for j in l];
    data.append(l)
n=len(data)
m=len(data[0])
print(n)
base=data;
test=data[15000:]
data=data[:15000];
test_label=label[15000:]
label=label[:15000]
n=len(data)
print(n)

17254
15000


In [0]:
# Ahhh Shit here we go again!
import numpy as np
n=len(data)
datt1=[];
datt0=[]
for i in range(n):
    if(label[i] ==1):
        datt1.append(data[i])
    else:
        datt0.append(data[i])

        
d1=np.array(datt1).T
cov1=np.cov(d1)
print(cov1);


d0=np.array(datt0).T
cov0=np.cov(d0)
# print(cov0);


print(cov0,cov1);


[[ 1.27781792 -0.12372494 -0.28784829]
 [-0.12372494  0.82899382  0.0105232 ]
 [-0.28784829  0.0105232   0.84445551]]
[[ 1.86253174 -0.09529292  0.08573331]
 [-0.09529292  1.48407412  0.00291071]
 [ 0.08573331  0.00291071  1.27214683]] [[ 1.27781792 -0.12372494 -0.28784829]
 [-0.12372494  0.82899382  0.0105232 ]
 [-0.28784829  0.0105232   0.84445551]]


In [0]:
inv1=np.linalg.inv(cov1)
inv0=np.linalg.inv(cov0)
print(inv1)
print(inv0)


[[0.86037318 0.12470515 0.29172011]
 [0.12470515 1.2245476  0.02724833]
 [0.29172011 0.02724833 1.28329366]]
[[ 0.54036239  0.03476844 -0.03649599]
 [ 0.03476844  0.67606091 -0.00388999]
 [-0.03649599 -0.00388999  0.78854124]]


In [0]:
n0=len(datt0)
n1=len(datt1)
d=len(data[0])
mean0=[0]*d
for i in range(n0):
    for j in range(d):
        mean0[j]+=datt0[i][j]
print(mean0)
for i in range(d):
    mean0[i]=mean0[i]/n0;
print(mean0)



mean1=[0]*d
for i in range(n1):
    for j in range(d):
        mean1[j]+=datt1[i][j]
print(mean1)
for i in range(d):
    mean1[i]=mean1[i]/n1;
print(mean1)


[3039.064156422655, 928.9992773832827, -124.60923202253232]
[0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-4498.887826481924, -1528.0733621822617, -12.162686064461266]
[-0.9905081079880943, -0.3364318278692782, -0.0026778260820038012]


In [0]:
det0=1/np.linalg.det(cov0)
det1=1/np.linalg.det(cov1)
L0=[mean0,inv0,det0]
L1=[mean1,inv1,det1]
Y0=label.count(0)/n;
Y1=label.count(1)/n
print(Y1,Y0)
import math
def predict(x):
    pp=np.array(x)-np.array(mean0);
    tt=np.dot(pp,inv0)
    tt=np.dot(tt,pp.T)
    tt=math.exp((-1/2)*tt);
    f0=(0.3989)*(L0[-1]*tt)*Y0;
    pp=np.array(x)-np.array(mean1);
    tt=np.dot(pp,inv1)
    tt=np.dot(tt,pp.T)
    tt=math.exp((-1/2)*tt);
    f1=(0.3989)*(L1[-1]*tt)*Y1;
    if(f1>f0):
        return 1;
    else:
        return 0
print(predict(data[0]))
print(label[0])    
    
    

2.0150842945874 4.6397515527950315
[1.0670882126680754, 0.11375582954154148, -1.8109290351554157] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
0
0


In [0]:
ans=[]
count=0;
label=[int(i) for i in label]
n=len(test)
for i in range(n):
    if(len(test[i])==3):
        ans.append(predict(test[i]))
        if(ans[i]==test_label[i]):
            count+=1;
print(count/n)
# print(ans.count(0))
# print(label.count(0))

[-1.1835992991631514, -0.49373968595556983, 0.4127066200078508] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-0.856996267046384, -0.23919534758444586, 0.6900157735151021] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-0.13086191348553747, 3.225869345295435, -0.33197344762694775] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-1.1818911468514246, -1.8138393576820584, -0.8697566679624846] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-1.1100919752024114, 0.5468255155878179, -0.7304878378434405] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[1.4307888627624996, -0.5440144541796248, -2.7007140745029345] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-1.7610407961749734, 0.0012446041344739993, -0.34391549244271] [0.2905970698434361, 0.08883144744533206, -0.011915206733843213]
[-0.5759950693853234, 0.3563454985204319, -0.11773832039868047] [0.2905970698434361, 0.0888314474453